### ISSUE TITLE
Does not enter name

### ISSUE THREAD

**Issue by andy9775** [ymotongpoo/vsc-licenser#4] opened 2016-06-30 20:20 UTC
Hey, I have the following setup for my settings.json file in the project directory root:

```
{
  "licenser.license": "AL2",
  "licenser.author": "Andy Chrzaszcz"
}
```

The issue is that while the license file and header are created, it inserts John Doe in the header rather than my name.

This is in VS code insiders 1.3.0 on OSX

**Comment by ymotongpoo** [comment] 2016-07-01 05:16
Thank you for your report. I reproduced the issue on my environment (VS Code insider 1.3.0 on OS X 10.11.5) as well.

Is license type correctly selected in your environment? I mean, is only "licenser.author" not recognized?

**Comment by andy9775** [comment] 2016-07-01 05:43
The license is recognized fine and shows up, its just the name inside of the license header that ends up being 'John Doe'

**Comment by ymotongpoo** [comment] 2016-07-01 10:41
Let me confirm one thing: are you using both stable version and insider version? These 2 versions are not sharing the settings.

When I set "licenser.author" for insider version, i.e. 1.3.0 this time, it worked fine.

**Comment by andy9775** [comment] 2016-07-01 15:57
I'm just using insiders, haven't tried it on stable (regular) so I can't comment

**Comment by ymotongpoo** [comment] 2016-07-02 04:07
@andy9775 Thanks for checking. Unfortunately, I couldn't reproduce the situation, so hard to find the cause. But I changed to use OS username as default author name that is more meaningful than "John Doe".

**Comment by ymotongpoo** [comment] 2017-02-09 01:55
No update for last 6 months. Closing this issue.

**Closed by ymotongpoo** 2017-02-09 01:55 UTC
Labels: need repro report
